= Repair Café Altdorf: Philosophie
:linkcss:
:stylesdir: styles
:disable-javascript:
:docinfo1:
:icons:
:imagesdir: images
:keywords: Repair Cafe, Altdorf, Nürnberg, reparieren, wegwerfen
:description: Repair Cafe in Altdorf bei Nürnberg

include::head-area.include[]

== Repair Café Altdorf: Unsere Philosophie

Damit Reparaturwissen nicht verloren geht, hat die Amsterdammer
Journalistin Martine Postma 2007 das erste Repair-Café „erfunden“.
Hierhin kommen Menschen mit ihren kaputten Sachen, die man vielleicht
noch reparieren kann. Aber wie? Hier treffen sie dann Menschen, die
gerne beim Reparieren helfen. Das ist keine Service-Station, bei der
man das Gerät abgibt und dann repariert wieder abholt. Nein, es wird beim
Selber-Reparieren geholfen. Gemeinsam wird geschaut, was kaputt sein
könnte, und wie man, meistens mit einfachen Mitteln, mit Tricks und
Improvisationsgeschick das Gerät wieder zum Funktionieren bringt. Wenn
der Föhn dann wieder föhnt, der Toaster wieder toastet, ist das ein
Erfolgserlebnis der besonderen Art: Man hat selber etwas wieder in
Ordnung gebracht, muss nichts wegwerfen oder was Neues kaufen. Und es
wurde ein bisschen Reparaturwissen weiter gegeben.

In Altdorf wollen die Initiatoren auch so eine Einrichtung auf den Weg
bringen. Es ist eine Initiative von Menschen, die einen Beitrag gegen
die Wegwerf- und „Immer-mehr-Wachstumsmentalität“ leisten wollen. Zum
ersten Repair-Café können Haushaltsgeräte mit elektrischen oder
mechanischen Defekten gebracht werden. Darauf sind die anwesenden
Reparatur-Helfer eingestellt. Sie stellen nicht nur ihr Wissen, ihre
Erfahrung und ihr Können kostenlos zur Verfügung, sie haben auch die
entsprechenden Werkzeuge dabei. Es gibt natürlich keine Garantie, dass
das mitgebrachte Gerät wieder repariert werden kann. Aber man hat es
wenigsten probiert.
