= Fürstenschlagverein Altdorf: Termine
:linkcss:
:stylesdir: styles
:disable-javascript:
:docinfo1:
:icons:
:imagesdir: images
:keywords: Fürstenschlagverein, Altdorf, Nürnberg, Vorstadtverein
:description: Fürstenschlagverein in Altdorf bei Nürnberg

include::head-area.include[]


////
=== [red]*Achtung! Alle Termine stehen weiterhin unter Corona-Vorbehalt!*
////

////
=== Sonntag, den 1. Oktober: Hof-Flohmarkt im Fürstenschlag 

Uhrzeit: 15-18 Uhr

Es ist ganz einfach, teilzunehmen: Stellt einfach einen Tisch vor eurem Haus (Privatwege und Privatgrund) auf, auf dem ihr eure Waren präsentieren könnt 
(kein kommerzieller Verkauf!). Denkt daran, eure Preise festzulegen und Geld für Wechselgeld bereitzuhalten. +

Wenn ihr keinen eigenen Verkaufsstand aufstellen möchtet, könnt ihr gerne als Besucher vorbeischauen, stöbern und mit euren Nachbarn plaudern. Vielleicht findet ihr 
das perfekte Schnäppchen! +

Bitte meldet euch bis 25.09.2023 bei uns an, wenn ihr einen Verkaufsstand aufstellen möchtet, damit wir eine kleine Übersicht der einzelnen Stände im Fürstenschlag 
erstellen können. Anmeldung über den folgenden Link: https://forms.office.com/r/8k3hd3xyb3
////

=== Freitag, den 8. Dezember: Nikolausfeier am Kinderspielplatz

////
++++
<p>&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Einladung_Nikolausfeier2022.pdf" target="_blank"><strong>Freitag, den 9. Dezember: Nikolausfeier im Fürstenschlag</strong></a></p>
++++
////