= Fürstenschlagverein Altdorf: Termine
:linkcss:
:stylesdir: styles
:disable-javascript:
:docinfo1:
:icons:
:imagesdir: images
:keywords: Fürstenschlagverein, Altdorf, Nürnberg, Vorstadtverein
:description: Fürstenschlagverein in Altdorf bei Nürnberg

include::head-area.include[]


////
=== [red]*Achtung! Alle Termine stehen weiterhin unter Corona-Vorbehalt!*
////

////
********* Auskommentiert fürs nächste mal ************
=== Sonntag, den 1. Oktober: Hof-Flohmarkt im Fürstenschlag 

Uhrzeit: 15-18 Uhr

Es ist ganz einfach, teilzunehmen: Stellt einfach einen Tisch vor eurem Haus (Privatwege und Privatgrund) auf, auf dem ihr eure Waren präsentieren könnt 
(kein kommerzieller Verkauf!). Denkt daran, eure Preise festzulegen und Geld für Wechselgeld bereitzuhalten. +

Wenn ihr keinen eigenen Verkaufsstand aufstellen möchtet, könnt ihr gerne als Besucher vorbeischauen, stöbern und mit euren Nachbarn plaudern. Vielleicht findet ihr 
das perfekte Schnäppchen! +

Bitte meldet euch bis 25.09.2023 bei uns an, wenn ihr einen Verkaufsstand aufstellen möchtet, damit wir eine kleine Übersicht der einzelnen Stände im Fürstenschlag 
erstellen können. Anmeldung über den folgenden Link: https://forms.office.com/r/8k3hd3xyb3
******************************************************
////

////  
********* Auskommentiert fürs nächste mal ************
=== Samstag, den 3. August: link:downloads/Picknick_im_Wald-2024.pdf[Picknick mit der Familie im Wald]
Start um 14:30 Uhr auf dem Bolzplatz vor dem WLG-Heizhaus +
Was erwartet euch?

- Picknick im Grünen: Bringt eure Lieblingsspeisen mit und genießt ein gemeinsames Essen in der Natur.
- Hütten- und Höhlenbau: Kreativ werden und eigene Unterkünfte aus Naturmaterialien errichten.
- Basteln mit Naturmaterialien: Spannende Bastelaktionen für Groß und Klein.

Anmeldung bitte bis 1. August per E-Mail an jasmin.gross@fuerstenschlag-verein.de !
*******************************************************
////

=== Dienstag, den 5. November: link:downloads/Energieabend-Plakat.pdf[*Energieabend des Fürstenschlagvereins*] 
Themen: link:downloads/Rundschreiben_2024_10_05.pdf[Gebäudesanierung, PV-Anlagen, Heizen mit der WLG]

=== Freitag, den 6. Dezember: Nikolausfeier am Kinderspielplatz

////
++++
<p>&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Einladung_Nikolausfeier2022.pdf" target="_blank"><strong>Freitag, den 9. Dezember: Nikolausfeier im Fürstenschlag</strong></a></p>
++++
////