= Fürstenschlagverein Altdorf: Nützliches
:linkcss:
:stylesdir: styles
:disable-javascript:
:docinfo1:
:icons:
:imagesdir: images
:keywords: Fürstenschlag, Altdorf, Nürnberg, Tipps, Vorstadtverein
:description: Fürstenschlagverein in Altdorf bei Nürnberg

include::head-area.include[]

== Fürstenschlagverein Altdorf: Nützliches
In der Rubrik Nützliches finden Sie

++++
&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Aufnahmeunterlagen_komplett.pdf" target="_blank">Beitrittserklärung, SEPA-Anhang und Datenschutzerklärung (.pdf Datei)</a>
<p style="margin-left:30px">Die Beitritts-, die Datenschutzerklärung (und ggf.das SEPA Lastschriftmandat) sind unterschrieben bei einem der Vorstandsmitglieder abzugeben</p>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Geraeteliste_aktuell.pdf" target="_blank">aktuelle_Geräteliste_des_Fürstenschlagvereins</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Flyer_Fuerstenschlagverein-Altdorf.pdf" target="_blank">Flyer des Fürstenschlagvereins (.pdf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/WLGHeizkostenabrechnung.pdf" target="_blank">Infos zur Heizkostenabrechnung der WLG (.pdf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Info_zum_Stromtarif_A-PLUS-vereint.pdf" target="_blank">Infos zum Stromtarif "A-PLUS vereint" (.pdf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Stromlieferungsvertrag_A-PLUS_vereint_ohne_Preisblatt.pdf" target="_blank">Stromlieferungsvetrag "A-Plus vereint" (.pdf Datei)</a>
<p style="margin-left:30px">Vetrag ausdrucken, ausfüllen, unterschreiben und vor der Abgabe bei den Stadtwerken vom Vereinsvorstand die Mitgliedschaft bestätigen lassen.</p>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/WLG-Senderliste-TV.pdf" target="_blank">WLG Senderliste Fernsehen (.pdf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/WLG-Senderliste-Radio.pdf" target="_blank">WLG Senderliste Radio (.pf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Herzinfarkt_und_Schlaganfall.pdf" target="_blank">Informationen zur Früherkennung von Herzinfakt und Schlaganfall (.pdf Datei)</a><br/><br/>

&nbsp;&nbsp;&nbsp;&nbsp;°&nbsp;<a href="downloads/Satzung.pdf" target="_blank">Vereins-Satzung des Fürstenschlagvereins (.pdf Datei)</a><br/><br/>
++++
