name: github-actions
run-name: ${{ github.actor }} is doing GitHub Actions
on: [push]
jobs:
  homepage-build:
    runs-on: ubuntu-latest
    steps:
        - name: Run build script
        run: ./bin/scripts/build.bash
        shell: bash